name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout action
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install npm
        run: npm install
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: checkout action
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: test npm
        run: npm test
    
