name: call a reasuble workflow
on: 
    workflow_dispatch:

jobs:
    call-workflow-in-local-repo:
    
      uses: ./.github/workflows/ex4.yaml
      with: 
        config-path: .github/workflows/ex4-c.yaml 
        nodeversion: 18

  
    
  
